INSERT INTO hexaoracle.hexagram_line (hexagram_id,line_index,text_en,text_ko,text_zh) VALUES
	 (1,1,'Line 1: The hidden dragon should not be used.','초구: 잠룡은 쓰지 말라.','初九：潛龍勿用。'),
	 (1,2,'Line 2: The dragon appears in the field; it is beneficial to see the great man.','구이: 용이 밭에 나타나니, 대인을 뵈면 이롭다.','九二：見龍在田，利見大人。'),
	 (1,3,'Line 3: The noble one works diligently all day, and remains watchful at night; no fault.','구삼: 군자가 종일토록 건건히 힘쓰고, 저녁에는 두려워하듯 삼가니 허물이 없다.','九三：君子終日乾乾，夕惕若厲，无咎。'),
	 (1,4,'Line 4: The dragon leaps in the abyss; no fault.','구사: 혹은 연못에서 뛰니 허물이 없다.','九四：或躍在淵，无咎。'),
	 (1,5,'Line 5: The flying dragon is in the heavens; it is beneficial to see the great man.','구오: 나는 용이 하늘에 있으니, 대인을 뵈면 이롭다.','九五：飛龍在天，利見大人。'),
	 (1,6,'Line 6: The arrogant dragon will have cause for regret.','상구: 교만한 용은 뉘우침이 있다.','上九：亢龍有悔。'),
	 (2,1,'Line 1: Treading on frost, hard ice will come.','초육: 서리를 밟으면 단단한 얼음이 이른다.','初六：履霜，堅冰至。'),
	 (2,2,'Line 2: Straight, square, and great; without practice, nothing is unfavorable.','육이: 바르고 방정하고 크게 하면 익히지 않아도 이롭지 않음이 없다.','六二：直方大，不習无不利。'),
	 (2,3,'Line 3: Containing beauty is fitting; serving the king brings no achievement, yet there is completion.','육삼: 아름다움을 품어도 지킬 수 있으며, 혹 왕의 일을 좇아도 이루는 것은 없으나 끝맺음은 있다.','六三：含章可貞，或從王事，无成有終。'),
	 (2,4,'Line 4: Tying up the bag; no blame, no praise.','육사: 자루를 묶으면 허물도 없고 명예도 없다.','六四：括囊，无咎无譽。');
INSERT INTO hexaoracle.hexagram_line (hexagram_id,line_index,text_en,text_ko,text_zh) VALUES
	 (2,5,'Line 5: Yellow lower garment; great fortune.','육오: 누런 치마, 크게 길하다.','六五：黃裳，元吉。'),
	 (2,6,'Line 6: Dragons fight in the wild; their blood is black and yellow.','상육: 용이 들에서 싸우니 그 피가 검고 누렇다.','上六：龍戰于野，其血玄黃。'),
	 (3,1,'Line 1: Hesitation and lingering; it is beneficial to dwell in correctness, beneficial to establish feudal lords.','초구: 머뭇거림이 있으니, 바르게 거주함이 이롭고 제후를 세움이 이롭다.','初九：磐桓；利居貞，利建侯。'),
	 (3,2,'Line 2: Difficulty upon difficulty, turning back again and again; not bandits but a marriage alliance. The woman remains steadfast and does not marry; after ten years she marries.','육이: 둔하여 머뭇거리며, 말을 타도 자꾸 되돌아온다. 도적이 아니고 혼인하러 오는 것인데, 여자가 바르게 지키면 시집가지 않다가 십 년 뒤에야 시집간다.','六二：屯如邅如，乘馬班如；匪寇婚媾，女子貞不字，十年乃字。'),
	 (3,3,'Line 3: Chasing the deer without a forester, entering the forest alone; for the noble one, it is nearly better to give up. To proceed brings regret.','육삼: 사슴을 쫓으나 짐승치기가 없어 홀로 숲 속으로 들어가니, 군자는 그만두는 것이 나으니 나아가면 뉘우침이 있다.','六三：即鹿无虞，惟入于林中，君子幾不如舍，往吝。'),
	 (3,4,'Line 4: Riding a horse, turning back, seeking marriage; to proceed is fortunate, nothing is unfavorable.','육사: 말을 타고 되돌아오며 혼인을 구하니, 나아가면 길하여 이롭지 않음이 없다.','六四：乘馬班如，求婚媾；往吉，无不利。'),
	 (3,5,'Line 5: Difficulty holds back its richness; small persistence brings good fortune, great persistence brings misfortune.','구오: 둔하여 그 기름을 머금으니, 작게 바르게 하면 길하나 크게 바르게 하면 흉하다.','九五：屯其膏，小貞吉，大貞凶。'),
	 (3,6,'Line 6: Riding a horse, turning back; weeping tears of blood.','상육: 말을 타고 되돌아오며 피눈물을 흘린다.','上六：乘馬班如，泣血漣如。'),
	 (4,1,'Line 1: Enabling the ignorant; it is beneficial to use discipline, to remove shackles. To proceed brings regret.','초육: 어리석음을 열 때, 형벌을 쓰는 것이 이로우니, 차꼬를 벗기고 나아가면 뉘우침이 있다.','初六：發蒙，利用刑人，用說桎梏，以往吝。'),
	 (4,2,'Line 2: Embracing ignorance brings fortune; taking a wife brings fortune; the son is able to manage the household.','구이: 어리석음을 포용하니 길하다. 아내를 맞이하니 길하다. 아들이 집을 잘 다스린다.','九二：包蒙，吉；納婦，吉；子克家。');
INSERT INTO hexaoracle.hexagram_line (hexagram_id,line_index,text_en,text_ko,text_zh) VALUES
	 (4,3,'Line 3: Do not take this woman in marriage; seeing a wealthy man, she does not preserve herself. Nothing is favorable.','육삼: 여자를 취하지 마라. 부유한 남자를 보고도 몸을 지키지 못하니, 이로움이 없다.','六三：勿用取女；見金夫，不有躬，无攸利。'),
	 (4,4,'Line 4: Entangled in ignorance; there is regret.','육사: 어리석음에 곤궁하니 뉘우침이 있다.','六四：困蒙，吝。'),
	 (4,5,'Line 5: Childlike ignorance brings fortune.','육오: 어린 아이 같은 어리석음, 길하다.','六五：童蒙，吉。'),
	 (4,6,'Line 6: Dispelling ignorance; not favorable to be a bandit, favorable to resist bandits.','상구: 어리석음을 치되, 도둑이 되는 것은 이롭지 않고, 도둑을 막는 것은 이롭다.','上九：擊蒙，不利為寇，利御寇。'),
	 (5,1,'Line 1: Waiting in the outskirts; perseverance is beneficial, no fault.','초구: 교외에서 기다리니, 항상함을 지키면 이로우며 허물이 없다.','初九：需于郊，利用恒，无咎。'),
	 (5,2,'Line 2: Waiting on the sand; there is some small talk, but in the end fortune.','구이: 모래 위에서 기다리니, 작은 말다툼이 있으나 마침내 길하다.','九二：需于沙，小有言，終吉。'),
	 (5,3,'Line 3: Waiting in the mud; bandits arrive.','구삼: 진흙 속에서 기다리니 도적이 이른다.','九三：需于泥，致寇至。'),
	 (5,4,'Line 4: Waiting in the blood; emerging from the pit.','육사: 피 속에서 기다리니, 구멍에서 벗어난다.','六四：需于血，出自穴。'),
	 (5,5,'Line 5: Waiting with wine and food; perseverance brings fortune.','구오: 술과 음식을 두고 기다리니, 바르게 하면 길하다.','九五：需于酒食，貞吉。'),
	 (5,6,'Line 6: Entering the pit; unexpected guests arrive, three in number. Honor them, and in the end, fortune.','상육: 구멍 속에 들어가니, 청하지 않은 손님 세 사람이 와서, 그들을 공경하면 마침내 길하다.','上六：入于穴，有不速之客三人來，敬之終吉。');
INSERT INTO hexaoracle.hexagram_line (hexagram_id,line_index,text_en,text_ko,text_zh) VALUES
	 (6,1,'Line 1: Do not persist in your affairs; there will be small talk, but in the end, good fortune.','초육: 일을 오래 끌지 않으니 작은 말다툼이 있으나 마침내 길하다.','初六：不永所事，小有言，終吉。'),
	 (6,2,'Line 2: Unable to win the lawsuit; retreat and flee. With a town of three hundred households, there is no blame.','구이: 송사에서 이기지 못하고 돌아가 도망하니, 읍 사람 삼백 호가 있으므로 허물이 없다.','九二：不克訟，歸而逋，其邑人三百戶，无眚。'),
	 (6,3,'Line 3: Eating the old virtue; perseverance is dangerous, but in the end, good fortune. Serving the king brings no achievement.','육삼: 옛 덕을 먹으니 바르게 해도 위태롭지만, 마침내 길하다. 혹 왕의 일을 좇으나 성취함이 없다.','六三：食舊德，貞厲，終吉；或從王事，无成。'),
	 (6,4,'Line 4: Unable to win the lawsuit, but returning to obey orders; change and remain steadfast, fortune.','구사: 송사에서 이기지 못하나 명을 다시 따르니, 바르게 지키면 길하다.','九四：不克訟，復即命，渝安貞，吉。'),
	 (6,5,'Line 5: In conflict, great fortune.','구오: 송사에서 크게 길하다.','九五：訟，元吉。'),
	 (6,6,'Line 6: Perhaps awarded a leather belt, yet in one morning it is taken away three times.','상구: 혹은 큰 띠를 하사받으나, 아침에 세 번 빼앗긴다.','上九：或錫之鞶帶，終朝三褫之。'),
	 (7,1,'Line 1: The army goes forth with discipline; without order, misfortune.','초육: 군대를 출동시킴에 법도가 있어야 하니, 그렇지 않으면 흉하다.','初六：師出以律，否臧凶。'),
	 (7,2,'Line 2: In the midst of the army; good fortune, no blame. The king thrice bestows commands.','구이: 군대 가운데 있으니 길하여 허물이 없고, 임금이 세 번 명을 내리신다.','九二：在師中，吉，无咎，王三錫命。'),
	 (7,3,'Line 3: The army may carry corpses; misfortune.','육삼: 군대가 혹은 시체를 싣고 돌아오니 흉하다.','六三：師或輿尸，凶。'),
	 (7,4,'Line 4: The army encamps on the left; no blame.','육사: 군대가 좌측에 진을 치니 허물이 없다.','六四：師左次，无咎。');
INSERT INTO hexaoracle.hexagram_line (hexagram_id,line_index,text_en,text_ko,text_zh) VALUES
	 (7,5,'Line 5: There are game in the field; it is beneficial to capture what is spoken of, no blame. The elder son leads the army, good fortune; the younger brother carries corpses, even with perseverance, misfortune.','육오: 사냥터에 짐승이 있으니, 말한 것을 잡는 것이 이롭고 허물이 없다. 장자가 군대를 거느리면 길하고, 아우가 시체를 실으면 바르더라도 흉하다.','六五：田有禽，利執言，无咎；長子帥師，弟子輿尸，貞凶。'),
	 (7,6,'Line 6: The great ruler issues commands; founding states and securing families. Do not employ petty men.','상육: 대군이 명을 내리니, 나라를 열고 집안을 계승함이 있다. 소인은 쓰지 말라.','上六：大君有命，開國承家，小人勿用。'),
	 (8,1,'Line 1: Holding together with sincerity, no blame. Sincerity fills the vessel; in the end comes further good fortune.','초육: 믿음을 가지고 서로 친하면 허물이 없으며, 믿음이 항아리에 가득하니 마침내 다른 길한 일이 온다.','初六：有孚比之，无咎；有孚盈缶，終來有他吉。'),
	 (8,2,'Line 2: Holding together from within; perseverance brings good fortune.','육이: 안으로부터 친하니 바르면 길하다.','六二：比之自內，貞吉。'),
	 (8,3,'Line 3: Holding together with the wrong people.','육삼: 사람과 친하지 않는다.','六三：比之匪人。'),
	 (8,4,'Line 4: Holding together outwardly; perseverance brings good fortune.','육사: 밖으로 친하니 바르면 길하다.','六四：外比之，貞吉。'),
	 (8,5,'Line 5: Manifest union. The king uses three drives and loses the game in front; the townsfolk need no warning, good fortune.','구오: 드러나게 친하니, 임금이 세 번 사냥을 벌여 앞의 짐승은 놓쳤으나, 읍 사람들이 경계하지 않아도 길하다.','九五：顯比，王用三驅，失前禽；邑人不誡，吉。'),
	 (8,6,'Line 6: Union without a head; misfortune.','상육: 친함에 머리가 없으니 흉하다.','上六：比之无首，凶。'),
	 (9,1,'Line 1: Returning to the path by oneself; what blame could there be? Good fortune.','초구: 스스로 도에서 돌아오니 어찌 허물이 있겠는가? 길하다.','初九：復自道，何其咎？吉。'),
	 (9,2,'Line 2: Being led back; good fortune.','구이: 이끌려 돌아오니 길하다.','九二：牽復，吉。');
INSERT INTO hexaoracle.hexagram_line (hexagram_id,line_index,text_en,text_ko,text_zh) VALUES
	 (9,3,'Line 3: The spokes are taken from the wagon; husband and wife turn away from each other.','구삼: 수레의 바퀴살이 빠지니 부부가 서로 등을 돌린다.','九三：輿說輻，夫妻反目。'),
	 (9,4,'Line 4: With sincerity, blood departs and fear gives way; no blame.','육사: 믿음이 있으니 피가 그치고 두려움이 사라져 허물이 없다.','六四：有孚，血去惕出，无咎。'),
	 (9,5,'Line 5: With sincerity bound together, one is enriched by neighbors.','구오: 믿음이 있어 함께 얽히니, 이웃과 더불어 부유하다.','九五：有孚攣如，富以其鄰。'),
	 (9,6,'Line 6: It has rained and been settled; virtue is esteemed and carried. The wife’s perseverance is dangerous. As the moon nears fullness, for the noble one to advance is misfortune.','상구: 비가 오고 자리를 잡으니, 덕이 존귀하게 실린다. 아내가 바르게 하면 위태롭다. 달이 거의 보름에 차면 군자가 나아가면 흉하다.','上九：既雨既處，尚德載，婦貞厲。月幾望，君子征凶。'),
	 (10,1,'Line 1: Simple treading; proceeding brings no blame.','초구: 소박하게 밟아 나아가니 허물이 없다.','初九：素履，往无咎。'),
	 (10,2,'Line 2: Treading the path is level and easy; the recluse holds firm, good fortune.','구이: 도를 밟음이 평탄하니, 은자가 바르게 지키면 길하다.','九二：履道坦坦，幽人貞吉。'),
	 (10,3,'Line 3: One-eyed can see, lame can tread. Treading on the tiger’s tail, it bites; misfortune. The warrior acts for the great prince.','육삼: 애꾸가 보며, 절름발이가 걸어간다. 호랑이 꼬리를 밟으니 물려 흉하다. 무인이 대군을 섬긴다.','六三：眇能視，跛能履；履虎尾，咥人，凶。武人為于大君。'),
	 (10,4,'Line 4: Treading on the tiger’s tail, anxious and cautious; in the end, good fortune.','구사: 호랑이 꼬리를 밟으니 두려워 떨지만 마침내 길하다.','九四：履虎尾，愬愬，終吉。'),
	 (10,5,'Line 5: Resolute treading; perseverance brings danger.','구오: 과감히 밟아 나아가니 바르더라도 위태롭다.','九五：夬履，貞厲。'),
	 (10,6,'Line 6: Observing the conduct and examining the omens; turning back brings great fortune.','상구: 밟음을 살펴 길흉을 상고하니, 되돌아옴이 크게 길하다.','上九：視履考祥，其旋元吉。');
INSERT INTO hexaoracle.hexagram_line (hexagram_id,line_index,text_en,text_ko,text_zh) VALUES
	 (11,1,'Line 1: Pulling up roots of grass, the clumps come with it; to advance brings good fortune.','초구: 띠풀을 뿌리째 뽑으면 그 무리가 함께 나오니, 나아가면 길하다.','初九：拔茅茹，以其彙，征吉。'),
	 (11,2,'Line 2: Embracing the wasteland, crossing the great river; not neglecting the distant. Though companions are lost, honor is gained in the central way.','구이: 황무지를 포용하고, 큰 강을 건너며, 멀리 있는 것도 버리지 않으니, 벗을 잃더라도 중도의 덕을 높인다.','九二：包荒，用馮河，不遐遺，朋亡，得尚于中行。'),
	 (11,3,'Line 3: No level ground without slope, no going without return; difficulty with perseverance brings no blame. Do not worry about sincerity; there is blessing in eating.','구삼: 평탄함이 없으면 기울어짐이 없고, 가는 곳마다 돌아옴이 있으니, 어렵더라도 바르게 하면 허물이 없다. 믿음을 근심하지 말라, 먹음에 복이 있다.','九三：无平不陂，无往不復，艱貞无咎。勿恤其孚，于食有福。'),
	 (11,4,'Line 4: Fluttering; not rich together with neighbors, yet without admonition there is trust.','육사: 펄펄 날아 이웃과 함께 부유하지 않으나, 경계하지 않아도 믿음이 있다.','六四：翩翩，不富以其鄰，不戒以孚。'),
	 (11,5,'Line 5: The sovereign Yi marries off his younger sister; with blessing, great fortune.','육오: 제을이 누이를 시집보내니, 큰 복이 있어 크게 길하다.','六五：帝乙歸妹，以祉元吉。'),
	 (11,6,'Line 6: The city wall falls back into the moat; do not use the army. From the town comes one’s own decree; perseverance brings regret.','상육: 성이 도랑으로 무너졌으니 군대를 쓰지 말고, 읍에서 스스로 명을 알리면 바르더라도 뉘우침이 있다.','上六：城復于隍，勿用師，自邑告命，貞吝。'),
	 (12,1,'Line 1: Pulling up roots of grass, the clumps come with it; perseverance brings good fortune and success.','초육: 띠풀을 뿌리째 뽑으면 그 무리가 함께 나오니, 바르게 하면 길하고 형통하다.','初六：拔茅茹，以其彙，貞吉，亨。'),
	 (12,2,'Line 2: Embracing and bearing; good fortune for the small man, obstruction for the great man, success is hindered.','육이: 작은 이를 포용하면 길하나, 큰 사람에게는 막힘이 있으니 형통하지 못하다.','六二：包承，小人吉，大人否，亨。'),
	 (12,3,'Line 3: Bearing shame.','육삼: 수치를 포용한다.','六三：包羞。'),
	 (12,4,'Line 4: There is mandate; no blame. Companions part from blessing.','구사: 명을 받으니 허물이 없고, 벗이 복을 떠난다.','九四：有命，无咎，疇離祉。');
INSERT INTO hexaoracle.hexagram_line (hexagram_id,line_index,text_en,text_ko,text_zh) VALUES
	 (12,5,'Line 5: Resting from obstruction; for the great man, good fortune. Guarding against loss, tie it to a clump of mulberry trees.','구오: 막힘을 쉬니, 대인은 길하다. 없어짐을 막으려면, 뽕나무에 매어야 한다.','九五：休否，大人吉；其亡其亡，繫于苞桑。'),
	 (12,6,'Line 6: The obstruction is overturned; first obstruction, then joy.','상구: 막힘이 기울어지니, 먼저 막힘이 있고 나중에 기쁨이 있다.','上九：傾否，先否後喜。'),
	 (13,1,'Line 1: Fellowship with men at the gate; no blame.','초구: 문에서 사람들과 사귀니 허물이 없다.','初九：同人于門，无咎。'),
	 (13,2,'Line 2: Fellowship with men in the clan; regret.','육이: 종친들과 사귀니 인색하다.','六二：同人于宗，吝。'),
	 (13,3,'Line 3: Hiding weapons in the grass, ascending the high hill; for three years they do not rise.','구삼: 무기를 풀숲에 감추고 높은 언덕에 올라가니, 삼 년 동안 일어나지 못한다.','九三：伏戎于莽，升其高陵，三歲不興。'),
	 (13,4,'Line 4: Climbing the wall, unable to attack; good fortune.','구사: 성벽에 올라가지만 공격하지 않으니 길하다.','九四：乘其墉，弗克攻，吉。'),
	 (13,5,'Line 5: Fellowship with men; first wailing and weeping, then laughter. The great army is victorious; they meet.','구오: 사람들과 사귀되, 먼저는 크게 울부짖고 후에는 웃으니, 대군이 이겨 서로 만난다.','九五：同人，先號咷而後笑，大師克，相遇。'),
	 (13,6,'Line 6: Fellowship with men in the open fields; no regret.','상구: 들에서 사람들과 사귀니 뉘우침이 없다.','上九：同人于郊，无悔。'),
	 (14,1,'Line 1: No interaction with harm, not a fault; in hardship, no blame.','초구: 서로 해치지 않으니 허물이 아니며, 어려움이 있으면 허물이 없다.','初九：无交害，匪咎；艱則无咎。'),
	 (14,2,'Line 2: A great cart carries the load; wherever one goes, no blame.','구이: 큰 수레에 실어 나아가니 허물이 없다.','九二：大車以載，有攸往，无咎。');
INSERT INTO hexaoracle.hexagram_line (hexagram_id,line_index,text_en,text_ko,text_zh) VALUES
	 (14,3,'Line 3: A prince offers sacrifice to the Son of Heaven; the petty man cannot accomplish this.','구삼: 공이 천자에게 제사를 드리니, 소인은 능히 감당하지 못한다.','九三：公用亨于天子，小人弗克。'),
	 (14,4,'Line 4: Not relying on one’s abundance; no blame.','구사: 그의 두터움을 믿지 않으니 허물이 없다.','九四：匪其彭，无咎。'),
	 (14,5,'Line 5: Sincerity united, awe-inspiring; good fortune.','육오: 그 믿음이 서로 사귀듯하고 위엄이 있으니 길하다.','六五：厥孚交如，威如；吉。'),
	 (14,6,'Line 6: From heaven comes help; good fortune, nothing not beneficial.','상구: 하늘이 스스로 도우니 길하여 이롭지 않음이 없다.','上九：自天祐之，吉无不利。'),
	 (15,1,'Line 1: A modest noble one crosses the great river; good fortune.','초육: 겸손한 군자가 큰 내를 건너니 길하다.','初六：謙謙君子，用涉大川，吉。'),
	 (15,2,'Line 2: Proclaiming modesty; perseverance brings good fortune.','육이: 겸손을 드러내니 바르면 길하다.','六二：鳴謙，貞吉。'),
	 (15,3,'Line 3: Working modestly; the noble one brings things to completion, good fortune.','구삼: 수고로이 겸손하니 군자가 끝까지 지켜 길하다.','九三：勞謙，君子有終，吉。'),
	 (15,4,'Line 4: Nothing not beneficial; displaying modesty.','육사: 이롭지 않음이 없으니, 겸손을 떨친다.','六四：无不利，撝謙。'),
	 (15,5,'Line 5: Not enriched together with neighbors; advantageous to undertake punitive expeditions, nothing not beneficial.','육오: 이웃과 더불어 부유하지 않으나, 침벌을 행함이 이로우니 이롭지 않음이 없다.','六五：不富以其鄰，利用侵伐，无不利。'),
	 (15,6,'Line 6: Proclaiming modesty; advantageous to mobilize the army and attack the town or state.','상구: 겸손을 드러내어 군사를 행하니, 읍나라를 정벌함이 이롭다.','上六：鳴謙，利用行師，征邑國。');
INSERT INTO hexaoracle.hexagram_line (hexagram_id,line_index,text_en,text_ko,text_zh) VALUES
	 (16,1,'Line 1: Noisy enthusiasm; misfortune.','초육: 기뻐함을 소리내니 흉하다.','初六：鳴豫，凶。'),
	 (16,2,'Line 2: Firm as a rock; not the whole day, perseverance brings good fortune.','육이: 돌처럼 굳세니 하루를 채우지 않아도 바르게 하면 길하다.','六二：介于石，不終日，貞吉。'),
	 (16,3,'Line 3: Looking upward in indulgent joy; regret. Delay brings regret.','육삼: 눈을 치켜뜨며 기뻐하니 뉘우침이 있다. 늦으면 더욱 뉘우침이 있다.','六三：盱豫，悔。遲有悔。'),
	 (16,4,'Line 4: Following joy brings great gain; do not doubt, companions gather like hair clasped by a pin.','구사: 기쁨을 따르니 크게 얻는다. 의심하지 말라, 벗들이 모여든다.','九四：由豫，大有得；勿疑，朋盍簪。'),
	 (16,5,'Line 5: Perseverance brings illness, but one does not die permanently.','육오: 바르게 하여도 병이 있으나, 오래도록 죽지 않는다.','六五：貞疾，恒不死。'),
	 (16,6,'Line 6: Enthusiasm in darkness; completion brings change, no blame.','상구: 어둡게 기뻐하니, 이루어져 변하면 허물이 없다.','上六：冥豫，成有渝，无咎。'),
	 (17,1,'Line 1: Change in office; perseverance brings good fortune. Going out the gate to associate brings merit.','초구: 벼슬이 변하니 바르게 하면 길하다. 문을 나서서 사귀면 공이 있다.','初九：官有渝，貞吉；出門交有功。'),
	 (17,2,'Line 2: Attached to the little one, losing the great man.','육이: 소자에게 매이니 장부를 잃는다.','六二：係小子，失丈夫。'),
	 (17,3,'Line 3: Attached to the great man, losing the little one. Following brings what is sought, gain. It is beneficial to remain steadfast.','육삼: 장부에게 매이니 소자를 잃는다. 따름에 구함이 있으면 얻는다. 바르게 거주함이 이롭다.','六三：係丈夫，失小子；隨有求，得。利居貞。'),
	 (17,4,'Line 4: Following brings gain, but perseverance leads to misfortune. With sincerity in the way and clarity, what blame can there be?','구사: 따름에 얻음이 있으나, 바르면 흉하다. 도에 믿음이 있어 밝게 하면 어찌 허물이 있으랴?','九四：隨有獲，貞凶。有孚在道，以明，何咎？');
INSERT INTO hexaoracle.hexagram_line (hexagram_id,line_index,text_en,text_ko,text_zh) VALUES
	 (17,5,'Line 5: Sincerity in what is excellent; good fortune.','구오: 아름다움에 성실하니 길하다.','九五：孚于嘉，吉。'),
	 (17,6,'Line 6: Bound and attached; in the end it follows and is linked. The king offers sacrifice on the western mountain; success.','상구: 붙잡아 매니 마침내 좇아 이어지니, 왕이 서산에서 제사를 드려 형통하다.','上六：拘系之，乃從維之。王用亨于西山。'),
	 (18,1,'Line 1: Correcting the father’s decay; if the son is diligent, no blame. Though dangerous, in the end good fortune.','초육: 아버지의 허물을 바로잡으니, 아들이 살피는 바가 있어 허물이 없고, 위태로워도 마침내 길하다.','初六：幹父之蠱，有子考，无咎；厲終吉。'),
	 (18,2,'Line 2: Correcting the mother’s decay; perseverance is not appropriate.','구이: 어머니의 허물을 바로잡으니 바르게 할 수 없다.','九二：幹母之蠱，不可貞。'),
	 (18,3,'Line 3: Correcting the father’s decay; some regret, but no great blame.','구삼: 아버지의 허물을 바로잡으니, 작은 뉘우침이 있으나 큰 허물은 없다.','九三：幹父之蠱，小有悔，无大咎。'),
	 (18,4,'Line 4: Indulging the father’s decay; going forward brings shame.','육사: 아버지의 허물을 관대히 여기니, 나아가면 인색함을 보게 된다.','六四：裕父之蠱，往見吝。'),
	 (18,5,'Line 5: Correcting the father’s decay; praise is gained.','육오: 아버지의 허물을 바로잡으니 칭송을 얻는다.','六五：幹父之蠱，用譽。'),
	 (18,6,'Line 6: Not serving kings or princes; one’s work is of lofty character.','상구: 왕이나 제후를 섬기지 않고, 그 일을 숭고히 한다.','上九：不事王侯，高尚其事。'),
	 (19,1,'Line 1: Approaching together; perseverance brings good fortune.','초구: 함께 임하니, 바르게 하면 길하다.','初九：咸臨，貞吉。'),
	 (19,2,'Line 2: Approaching together; good fortune, nothing not beneficial.','구이: 함께 임하니 길하고, 이롭지 않음이 없다.','九二：咸臨，吉，无不利。');
INSERT INTO hexaoracle.hexagram_line (hexagram_id,line_index,text_en,text_ko,text_zh) VALUES
	 (19,3,'Line 3: Approaching with sweetness; no advantage. When aware of the anxiety, no blame.','육삼: 달콤하게 임하니 이로움이 없다. 근심하면 허물이 없다.','六三：甘臨，无攸利；既憂之，无咎。'),
	 (19,4,'Line 4: Approaching with sincerity; no blame.','육사: 지극히 임하니 허물이 없다.','六四：至臨，无咎。'),
	 (19,5,'Line 5: Wise approach; fitting for a great ruler, good fortune.','육오: 지혜롭게 임하니, 대군의 마땅함이 있어 길하다.','六五：知臨，大君之宜，吉。'),
	 (19,6,'Line 6: Sincere approach; good fortune, no blame.','상구: 두터이 임하니, 길하고 허물이 없다.','上六：敦臨，吉，无咎。'),
	 (20,1,'Line 1: Childlike contemplation; for the petty man, no blame; for the noble one, regret.','초육: 어린아이처럼 봄이니, 소인은 허물이 없으나 군자는 인색하다.','初六：童觀，小人无咎，君子吝。'),
	 (20,2,'Line 2: Peeping contemplation; favorable for the woman’s perseverance.','육이: 엿보듯 봄이니, 여자가 바르게 하면 이롭다.','六二：闚觀，利女貞。'),
	 (20,3,'Line 3: Contemplating my own life; advancing and retreating.','육삼: 나의 삶을 관찰하니, 나아가고 물러남이 있다.','六三：觀我生，進退。'),
	 (20,4,'Line 4: Viewing the splendor of the kingdom; it is favorable to be a guest of the king.','육사: 나라의 빛을 보니, 왕에게 손님으로 나아감이 이롭다.','六四：觀國之光，利用賓于王。'),
	 (20,5,'Line 5: Contemplating my life; for the noble one, no blame.','구오: 나의 삶을 관찰하니, 군자는 허물이 없다.','九五：觀我生，君子无咎。'),
	 (20,6,'Line 6: Contemplating their life; for the noble one, no blame.','상구: 그의 삶을 관찰하니, 군자는 허물이 없다.','上九：觀其生，君子无咎。');
INSERT INTO hexaoracle.hexagram_line (hexagram_id,line_index,text_en,text_ko,text_zh) VALUES
	 (21,1,'Line 1: Biting through with wooden fetters on the feet, the toes are gone; no blame.','초구: 발목에 차꼬를 차 발가락이 없어지나 허물은 없다.','初九：履校滅趾，无咎。'),
	 (21,2,'Line 2: Biting through the flesh, the nose is gone; no blame.','육이: 살을 씹어 코가 없어지나 허물은 없다.','六二：噬膚滅鼻，无咎。'),
	 (21,3,'Line 3: Biting through dried meat, encountering poison; slight discomfort, no blame.','육삼: 말린 고기를 씹다가 독을 만나니, 작은 인색함이 있으나 허물은 없다.','六三：噬腊肉，遇毒；小吝，无咎。'),
	 (21,4,'Line 4: Biting through dry gristle, obtaining a metal arrow; perseverance in difficulty brings good fortune.','구사: 마른 고기를 씹다가 쇠 화살을 얻으니, 어렵더라도 바르게 하면 길하다.','九四：噬乾胏，得金矢，利艱貞，吉。'),
	 (21,5,'Line 5: Biting through dried meat, obtaining yellow gold; perseverance brings danger, yet no blame.','육오: 마른 고기를 씹다가 황금을 얻으니, 바르더라도 위태롭지만 허물은 없다.','六五：噬乾肉，得黃金，貞厲，无咎。'),
	 (21,6,'Line 6: Biting through with great wooden stocks, the ears are gone; misfortune.','상구: 큰 차꼬에 걸려 귀가 없어지니 흉하다.','上九：何校滅耳，凶。'),
	 (22,1,'Line 1: Adorning the toes; abandoning the carriage and walking.','초구: 발가락을 꾸미니 수레를 버리고 걸어간다.','初九：賁其趾，舍車而徒。'),
	 (22,2,'Line 2: Adorning the beard.','육이: 수염을 꾸민다.','六二：賁其須。'),
	 (22,3,'Line 3: Adorning in moist grace; enduring perseverance brings good fortune.','구삼: 꾸밈이 촉촉하니, 길게 바르게 하면 길하다.','九三：賁如濡如，永貞吉。'),
	 (22,4,'Line 4: Adorning in plain whiteness, like a white horse in flight; not a robber, but a suitor.','육사: 꾸밈이 희고 빛나니, 흰 말이 날아오듯 한다. 도적이 아니고 혼인하러 오는 것이다.','六四：賁如皤如，白馬翰如；匪寇婚媾。');
INSERT INTO hexaoracle.hexagram_line (hexagram_id,line_index,text_en,text_ko,text_zh) VALUES
	 (22,5,'Line 5: Adorning the hills and gardens; binding small bundles of silk. Though meager, in the end good fortune.','육오: 언덕과 동산을 꾸미며, 비단을 조금 묶어 보내니 인색하나, 마침내 길하다.','六五：賁于丘園，束帛戔戔，吝，終吉。'),
	 (22,6,'Line 6: Simple white adornment; no blame.','상구: 흰 꾸밈이니 허물이 없다.','上九：白賁，无咎。'),
	 (23,1,'Line 1: Stripping the bed by the feet; abolishing correctness brings misfortune.','초육: 침상을 발밑에서 깎으니, 바름을 없애면 흉하다.','初六：剝牀以足，蔑貞凶。'),
	 (23,2,'Line 2: Stripping the bed by the frame; abolishing correctness brings misfortune.','육이: 침상을 가장자기에서 깎으니, 바름을 없애면 흉하다.','六二：剝牀以辨，蔑貞凶。'),
	 (23,3,'Line 3: Stripping away; no blame.','육삼: 깎아내리니 허물이 없다.','六三：剝之，无咎。'),
	 (23,4,'Line 4: Stripping the bed to the skin; misfortune.','육사: 침상을 살까지 깎으니 흉하다.','六四：剝牀以膚，凶。'),
	 (23,5,'Line 5: Like stringing fish; with palace women as favor, nothing not beneficial.','육오: 물고기를 꿰듯 하니, 궁녀로 총애를 받으니 이롭지 않음이 없다.','六五：貫魚，以宮人寵，无不利。'),
	 (23,6,'Line 6: The large fruit is not eaten; the noble one gains a carriage, the petty man’s hut is stripped.','상구: 큰 열매를 먹지 않으니, 군자는 수레를 얻고 소인은 집이 깎인다.','上九：碩果不食，君子得輿，小人剝廬。'),
	 (24,1,'Line 1: Return not far; no remorse, great fortune.','초구: 멀리 가지 않고 돌아오니 진실한 뉘우침이 없으니 크게 길하다.','初九：不遠復，无祗悔，元吉。'),
	 (24,2,'Line 2: Restful return; good fortune.','육이: 평안히 돌아오니 길하다.','六二：休復，吉。');
INSERT INTO hexaoracle.hexagram_line (hexagram_id,line_index,text_en,text_ko,text_zh) VALUES
	 (24,3,'Line 3: Frequent return; danger, yet no blame.','육삼: 자주 돌아오니 위태로우나 허물은 없다.','六三：頻復，厲无咎。'),
	 (24,4,'Line 4: Walking in the midst, returning alone.','육사: 중도의 길로 홀로 돌아온다.','六四：中行獨復。'),
	 (24,5,'Line 5: Sincere return; no regret.','육오: 두터이 돌아오니 뉘우침이 없다.','六五：敦復，无悔。'),
	 (24,6,'Line 6: Confused return; misfortune, calamity. If an army is raised, it ends in great defeat. For the ruler of the state, misfortune. Even after ten years, unable to conquer.','상구: 미혹하여 돌아오니 흉하여 재앙이 있다. 군사를 일으켜도 끝내 크게 패하니, 그 나라 임금에게 흉하다. 십 년이 되어도 정벌할 수 없다.','上六：迷復，凶，有災眚。用行師，終有大敗；以其國君，凶；至于十年，不克征。'),
	 (25,1,'Line 1: Innocence; to advance brings good fortune.','초구: 허망함이 없으니 나아가면 길하다.','初九：无妄，往吉。'),
	 (25,2,'Line 2: Not plowing yet reaping, not clearing yet resting; thus it is beneficial to have somewhere to go.','육이: 밭을 갈지 않고 거두며, 개간하지 않고 묵히나, 나아감이 이롭다.','六二：不耕穫，不菑畬，則利有攸往。'),
	 (25,3,'Line 3: Calamity of innocence; a tethered ox is taken by a passerby. It is the townsman’s misfortune.','육삼: 허망한 재앙이 있어, 소가 묶였는데 행인이 그것을 얻으니 읍사람의 재앙이 된다.','六三：无妄之災，或繫之牛，行人之得，邑人之災。'),
	 (25,4,'Line 4: Perseverance is possible; no blame.','구사: 바르게 할 수 있으니 허물이 없다.','九四：可貞，无咎。'),
	 (25,5,'Line 5: Illness of innocence; do not use medicine, there is joy.','구오: 허망한 병이 있으나 약을 쓰지 않으니 기쁨이 있다.','九五：无妄之疾，勿藥有喜。'),
	 (25,6,'Line 6: Innocence; action brings misfortune, nothing is beneficial.','상구: 허망함이 없으나, 행함에 허물이 있어 이로움이 없다.','上九：无妄，行有眚，无攸利。');
INSERT INTO hexaoracle.hexagram_line (hexagram_id,line_index,text_en,text_ko,text_zh) VALUES
	 (26,1,'Line 1: There is danger; it is beneficial to stop oneself.','초구: 위태로움이 있으니 스스로 멈춤이 이롭다.','初九：有厲，利已。'),
	 (26,2,'Line 2: The wagon’s axle straps are removed.','구이: 수레의 바퀴 통이 빠졌다.','九二：輿說輹。'),
	 (26,3,'Line 3: Fine horses run; perseverance in difficulty is beneficial. Practicing with chariots and guards; beneficial to have somewhere to go.','구삼: 좋은 말이 달리니, 어렵더라도 바르게 함이 이롭다. 수레와 호위를 익히면 나아감이 이롭다.','九三：良馬逐，利艱貞，曰閑輿衛，利有攸往。'),
	 (26,4,'Line 4: A calf’s horns are blocked; great fortune.','육사: 송아지의 뿔을 막으니 크게 길하다.','六四：童牛之牿，元吉。'),
	 (26,5,'Line 5: The tusks of a gelded boar; good fortune.','육오: 거세한 돼지의 이빨이니 길하다.','六五：豶豕之牙，吉。'),
	 (26,6,'Line 6: Treading the great road of heaven; success.','상구: 하늘의 큰 길에 이르니 형통하다.','上九：何天之衢，亨。'),
	 (27,1,'Line 1: Abandoning your sacred tortoise, gazing only at my mouth; misfortune.','초구: 네 신령한 거북을 버리고 나의 입술만 바라보니 흉하다.','初九：舍爾靈龜，觀我朵頤，凶。'),
	 (27,2,'Line 2: Turning nourishment upside down, opposing the norm; feeding on a hill; to advance brings misfortune.','육이: 위로만 먹고, 도리를 어기며, 언덕에서 먹으니 나아가면 흉하다.','六二：顛頤，拂經，于丘頤，征凶。'),
	 (27,3,'Line 3: Opposing nourishment; perseverance brings misfortune. Do not act for ten years; nothing is beneficial.','육삼: 먹음을 어기니, 바르게 해도 흉하다. 십 년 동안 쓰지 말라, 이로움이 없다.','六三：拂頤，貞凶；十年勿用，无攸利。'),
	 (27,4,'Line 4: Turning nourishment upward brings fortune. Tiger’s gaze, intent and pursuing desire; no blame.','육사: 위로만 먹으니 길하다. 호랑이가 노려보듯, 그 욕망이 쫓아도 허물이 없다.','六四：顛頤，吉；虎視眈眈，其欲逐逐，无咎。');
INSERT INTO hexaoracle.hexagram_line (hexagram_id,line_index,text_en,text_ko,text_zh) VALUES
	 (27,5,'Line 5: Opposing the norm; dwelling in perseverance brings fortune, but do not cross the great river.','육오: 도리를 어기더라도, 바르게 거처하면 길하나, 큰 내를 건너는 것은 불가하다.','六五：拂經，居貞吉，不可涉大川。'),
	 (27,6,'Line 6: Following proper nourishment; though dangerous, good fortune. Beneficial to cross the great river.','상구: 올바른 먹음에 따르니, 위태로워도 길하다. 큰 내를 건넘이 이롭다.','上九：由頤，厲吉；利涉大川。'),
	 (28,1,'Line 1: Using white rushes for support; no blame.','초육: 흰 띠풀을 깔아 쓰니 허물이 없다.','初六：藉用白茅，无咎。'),
	 (28,2,'Line 2: The withered willow produces shoots; an old man takes a young wife; nothing not beneficial.','구이: 마른 버드나무에서 싹이 나니, 늙은이가 젊은 아내를 얻으니 이롭지 않음이 없다.','九二：枯楊生稊，老夫得其女妻，无不利。'),
	 (28,3,'Line 3: The ridgepole bends; misfortune.','구삼: 들보가 휘니 흉하다.','九三：棟橈，凶。'),
	 (28,4,'Line 4: The ridgepole has support; good fortune. If there are other matters, regret.','구사: 들보가 높으니 길하나, 다른 일이 있으면 인색하다.','九四：棟隆，吉；有它吝。'),
	 (28,5,'Line 5: The withered willow blossoms; an old woman takes a young husband; no blame, no praise.','구오: 마른 버드나무에 꽃이 피니, 늙은 여자가 젊은 남자를 얻으니 허물도 없고 칭송도 없다.','九五：枯楊生華，老婦得士夫，无咎无譽。'),
	 (28,6,'Line 6: Excessive crossing, drowning the head; misfortune, yet no blame.','상구: 물을 건너다 머리가 잠기니 흉하나 허물은 없다.','上六：過涉滅頂，凶，无咎。'),
	 (29,1,'Line 1: Repeated pitfalls; entering the pit within the abyss, misfortune.','초육: 함정에 익숙하여 깊은 구덩이에 빠지니 흉하다.','初六：習坎，入于坎窞，凶。'),
	 (29,2,'Line 2: The abyss is perilous; seeking small gains brings results.','구이: 험함이 있으나 작은 것을 구하면 얻는다.','九二：坎有險，求小得。');
INSERT INTO hexaoracle.hexagram_line (hexagram_id,line_index,text_en,text_ko,text_zh) VALUES
	 (29,3,'Line 3: Coming with repeated danger, perilous and resting; entering the pit within the abyss, do not act.','육삼: 오는 것이 험난하고 위태로워 깊은 구덩이에 들어가니 쓰지 말라.','六三：來之坎坎，險且枕，入于坎窞，勿用。'),
	 (29,4,'Line 4: A jug of wine, a bowl of rice in earthenware; accepting simplicity through the window, in the end no blame.','육사: 술 한 잔과 음식 두 그릇, 질그릇을 사용하여, 약속을 창으로 들이니 마침내 허물이 없다.','六四：樽酒簋貳，用缶，納約自牖，終无咎。'),
	 (29,5,'Line 5: The abyss not full, only level; no blame.','구오: 구덩이가 가득 차지 않고 거의 평평하니 허물이 없다.','九五：坎不盈，祇既平，无咎。'),
	 (29,6,'Line 6: Bound with cords and ropes, placed in thorn bushes; for three years not obtained, misfortune.','상구: 가는 끈에 묶어 가시덤불에 두니, 삼 년 동안 얻지 못하니 흉하다.','上六：繫用徽纆，寘于叢棘，三歲不得，凶。'),
	 (30,1,'Line 1: Treading awkwardly; with reverence, no blame.','초구: 밟음이 어수선하니, 공경하면 허물이 없다.','初九：履錯然，敬之无咎。'),
	 (30,2,'Line 2: Yellow brightness; great fortune.','육이: 노란 빛이니 크게 길하다.','六二：黃離，元吉。'),
	 (30,3,'Line 3: The clinging at sunset; not drumming on pots and singing brings the lament of old age; misfortune.','구삼: 해가 서산에 기우는 불빛이니, 북을 치며 노래하지 않으면 늙은이의 탄식이니 흉하다.','九三：日昃之離，不鼓缶而歌，則大耋之嗟，凶。'),
	 (30,4,'Line 4: Suddenly it comes, blazing, dying, abandoned.','구사: 갑자기 달려들어 불태우고 죽이고 버린다.','九四：突如其來如，焚如，死如，棄如。'),
	 (30,5,'Line 5: Tears flow, sorrow and sighing; good fortune.','육오: 눈물을 흘리며 근심하고 탄식하니 길하다.','六五：出涕沱若，戚嗟若，吉。'),
	 (30,6,'Line 6: The king goes forth to campaign; captures the leader, not the followers; no blame.','상구: 왕이 군사를 출동하니 머리를 베어 공을 세우고, 그 무리를 사로잡으니 허물이 없다.','上九：王用出征，有嘉折首，獲匪其醜，无咎。');
INSERT INTO hexaoracle.hexagram_line (hexagram_id,line_index,text_en,text_ko,text_zh) VALUES
	 (31,1,'Line 1: Influence shows itself in the big toe.','초육: 엄지발가락에 감응한다.','初六：咸其拇。'),
	 (31,2,'Line 2: Influence shows itself in the calves; misfortune. If one abides, good fortune.','육이: 장딴지에 감응하니 흉하나, 머무르면 길하다.','六二：咸其腓，凶，居吉。'),
	 (31,3,'Line 3: Influence shows itself in the thighs; holding to what follows; going brings humiliation.','구삼: 넓적다리에 감응하니, 따라가 붙잡으니, 나아가면 인색하다.','九三：咸其股，執其隨，往吝。'),
	 (31,4,'Line 4: Perseverance brings good fortune, regret vanishes. Restless going and coming, companions follow your thoughts.','구사: 바르면 길하여 뉘우침이 없으니, 분주히 왕래하면 벗이 네 뜻을 따른다.','九四：貞吉，悔亡。憧憧往來，朋從爾思。'),
	 (31,5,'Line 5: Influence shows itself in the back; no regret.','구오: 등허리에 감응하니 뉘우침이 없다.','九五：咸其脢，无悔。'),
	 (31,6,'Line 6: Influence shows itself in the jaws, cheeks, and tongue.','상구: 뺨과 혀에 감응한다.','上六：咸其輔，頰舌。'),
	 (32,1,'Line 1: Lasting excessively; perseverance brings misfortune, nothing is beneficial.','초육: 오래함이 지나치니, 바르더라도 흉하고 이로움이 없다.','初六：浚恆，貞凶，无攸利。'),
	 (32,2,'Line 2: Regret disappears.','구이: 뉘우침이 없어진다.','九二：悔亡。'),
	 (32,3,'Line 3: If one does not persist in virtue, shame may result; perseverance brings disgrace.','구삼: 덕을 오래하지 못하면 수치를 당하니, 바르게 해도 인색하다.','九三：不恆其德，或承之羞，貞吝。'),
	 (32,4,'Line 4: No game in the field.','구사: 사냥터에 새가 없다.','九四：田无禽。');
INSERT INTO hexaoracle.hexagram_line (hexagram_id,line_index,text_en,text_ko,text_zh) VALUES
	 (32,5,'Line 5: Lasting in virtue; for the woman, perseverance brings good fortune, for the man, misfortune.','육오: 그 덕을 오래 지니니, 여자는 바르면 길하고 남자는 흉하다.','六五：恆其德，貞婦人吉，夫子凶。'),
	 (32,6,'Line 6: Restless duration; misfortune.','상구: 흔들리는 오래함이니 흉하다.','上六：振恆，凶。'),
	 (33,1,'Line 1: Retreating by the tail; danger. It is not beneficial to have somewhere to go.','초육: 꼬리로 물러남이니 위태로우니 나아감에 쓰지 말라.','初六：遯尾，厲，勿用有攸往。'),
	 (33,2,'Line 2: Bound with the hide of a yellow ox; none can loosen it.','육이: 누런 소 가죽으로 잡아 묶었으니, 능히 풀 수 없다.','六二：執之用黃牛之革，莫之勝說。'),
	 (33,3,'Line 3: Tied to retreat; illness and danger. Rearing servants and concubines brings good fortune.','구삼: 물러남에 매이니 병과 위태로움이 있으나, 신하와 첩을 기르면 길하다.','九三：係遯，有疾厲，畜臣妾吉。'),
	 (33,4,'Line 4: Enjoying retreat; for the noble one, good fortune; for the petty man, misfortune.','구사: 즐겨 물러남이니 군자는 길하고 소인은 불리하다.','九四：好遯，君子吉，小人否。'),
	 (33,5,'Line 5: Excellent retreat; perseverance brings good fortune.','구오: 아름다운 물러남이니, 바르면 길하다.','九五：嘉遯，貞吉。'),
	 (33,6,'Line 6: Comfortable retreat; nothing is unfavorable.','상구: 넉넉한 물러남이니 이롭지 않음이 없다.','上九：肥遯，无不利。'),
	 (34,1,'Line 1: Strength in the toes; to advance brings misfortune, but sincerity prevails.','초구: 발가락에 힘을 쓰니, 나아가면 흉하나 성실하면 된다.','初九：壯于趾，征凶，有孚。'),
	 (34,2,'Line 2: Perseverance brings good fortune.','구이: 바르게 하면 길하다.','九二：貞吉。');
INSERT INTO hexaoracle.hexagram_line (hexagram_id,line_index,text_en,text_ko,text_zh) VALUES
	 (34,3,'Line 3: The petty man uses strength, the noble one uses restraint. Perseverance brings danger. A ram butts against a fence and injures its horns.','구삼: 소인은 힘을 쓰고 군자는 그물로 다스리니, 바르면 위태롭다. 숫양이 울타리를 들이받아 뿔이 상한다.','九三：小人用壯，君子用罔；貞厲。羝羊觸藩，羸其角。'),
	 (34,4,'Line 4: Perseverance brings good fortune, regret vanishes. The fence is opened, yet no harm.','구사: 바르면 길하고, 뉘우침이 없으며, 울타리가 터져도 상하지 않는다.','九四：貞吉，悔亡；藩決不羸。'),
	 (34,5,'Line 5: Losing the ram on level ground; no regret.','육오: 양을 평지에서 잃으니 뉘우침이 없다.','六五：喪羊于易，无悔。'),
	 (34,6,'Line 6: A ram butts against a fence; unable to retreat, unable to advance, nothing is beneficial. In difficulty, good fortune.','상육: 숫양이 울타리를 들이받아 물러서지도 나아가지도 못하니, 이로움이 없다. 어려움 속에서는 길하다.','上六：羝羊觸藩，不能退，不能遂，无攸利。艱則吉。'),
	 (35,1,'Line 1: Advancement seems halted, yet perseverance brings good fortune. Without confidence, if tolerant, no blame.','초육: 나아감이 꺾이는 듯하나, 바르게 하면 길하다. 믿음을 얻지 못해도 여유 있으면 허물이 없다.','初六：晉如摧如，貞吉。罔孚，裕无咎。'),
	 (35,2,'Line 2: Advancement with anxiety; perseverance brings good fortune. Receiving great blessing from the ancestral mother.','육이: 나아감이 근심스러우나, 바르게 하면 길하다. 큰 복을 받아 왕모에게서 나온다.','六二：晉如愁如，貞吉。受兹介福，于其王母。'),
	 (35,3,'Line 3: With the trust of the people, regret vanishes.','육삼: 무리가 믿어주니, 뉘우침이 없어진다.','六三：眾允，悔亡。'),
	 (35,4,'Line 4: Advancement like a field rat; perseverance brings danger.','구사: 나아감이 쥐와 같으니, 바르게 해도 위태롭다.','九四：晉如鼫鼠，貞厲。'),
	 (35,5,'Line 5: Regret disappears; do not worry about loss or gain. To advance brings fortune, nothing is unfavorable.','육오: 뉘우침이 없어지니, 잃고 얻음을 근심하지 말라. 나아가면 길하고 이롭지 않음이 없다.','六五：悔亡，失得勿恤，往吉，无不利。'),
	 (35,6,'Line 6: Advancing with the horns; using it to attack the town. Dangerous yet good fortune, no blame. Perseverance brings regret.','상구: 뿔로 나아가듯 하여 읍을 정벌하니, 위태롭지만 길하고 허물은 없다. 그러나 바르더라도 인색하다.','上九：晉其角，維用伐邑，厲吉，无咎。貞吝。');
INSERT INTO hexaoracle.hexagram_line (hexagram_id,line_index,text_en,text_ko,text_zh) VALUES
	 (36,1,'Line 1: Darkening of the light as it flies, drooping its wings. The noble one on the journey goes three days without food; where he goes, the host has words.','초구: 밝음이 날아가 그 날개를 드리우니, 군자가 길을 가며 사흘을 먹지 않으니, 나아가는 곳에 주인이 말이 있다.','初九：明夷于飛，垂其翼；君子于行，三日不食，有攸往，主人有言。'),
	 (36,2,'Line 2: Darkening of the light injures the left thigh. With a strong horse one rescues; good fortune.','육이: 밝음이 어두워 왼쪽 넓적다리에 상함이 있으나, 건장한 말로 구하니 길하다.','六二：明夷，夷于左股，用拯馬壯，吉。'),
	 (36,3,'Line 3: Darkening of the light during a southern hunt; obtaining the great chief. Do not act with haste in perseverance.','구삼: 남쪽에서 사냥하다가 그 큰 우두머리를 얻으니, 바름을 급히 하지 말라.','九三：明夷于南狩，得其大首，不可疾貞。'),
	 (36,4,'Line 4: Entering the left belly, gaining the heart of the darkened one; exiting at the gate and courtyard.','육사: 왼쪽 배 속으로 들어가서, 밝음을 잃은 이의 마음을 얻어 문 앞에서 나온다.','六四：入于左腹，獲明夷之心，于出門庭。'),
	 (36,5,'Line 5: Darkening of the light like Prince Ji; perseverance is beneficial.','육오: 기자의 밝음이 어두워지니, 바름이 이롭다.','六五：箕子之明夷，利貞。'),
	 (36,6,'Line 6: Not bright but dark. At first ascending to heaven, later sinking into the earth.','상육: 밝지 않고 어두우니, 처음에는 하늘에 오르나 후에는 땅속에 들어간다.','上六：不明晦，初登于天，後入于地。'),
	 (37,1,'Line 1: Regulating the family; regret vanishes.','초구: 집안을 단속하니 뉘우침이 없어진다.','初九：閑有家，悔亡。'),
	 (37,2,'Line 2: No advance; she attends to the household meal. Perseverance brings good fortune.','육이: 나아감이 없으나, 안에서 음식을 맡으니 바르면 길하다.','六二：无攸遂，在中饋，貞吉。'),
	 (37,3,'Line 3: The family is strict; regret and danger, yet good fortune. If the wife and children are frivolous, in the end disgrace.','구삼: 집안사람이 엄격하면 뉘우침이 있고 위태로우나 길하다. 부인과 자식이 희희낙락하면 마침내 인색하다.','九三：家人嗃嗃，悔厲吉；婦子嘻嘻，終吝。'),
	 (37,4,'Line 4: Enriching the household; great fortune.','육사: 집안을 부유하게 하니 크게 길하다.','六四：富家，大吉。');
INSERT INTO hexaoracle.hexagram_line (hexagram_id,line_index,text_en,text_ko,text_zh) VALUES
	 (37,5,'Line 5: The king administers the household; no worry, good fortune.','구오: 왕이 집을 다스리니 근심하지 않아도 길하다.','九五：王假有家，勿恤，吉。'),
	 (37,6,'Line 6: With sincerity and majesty; in the end, good fortune.','상구: 믿음과 위엄이 있어 마침내 길하다.','上九：有孚威如，終吉。'),
	 (38,1,'Line 1: Regret disappears. Losing the horse, do not pursue; it returns of itself. Meeting the evil man, no blame.','초구: 뉘우침이 없어지니, 잃은 말을 좇지 않아도 스스로 돌아온다. 악인을 만나도 허물이 없다.','初九：悔亡，喪馬勿逐，自復。見惡人无咎。'),
	 (38,2,'Line 2: Encountering the lord in a narrow alley; no blame.','구이: 골목에서 주인을 만나니 허물이 없다.','九二：遇主于巷，无咎。'),
	 (38,3,'Line 3: Seeing the cart dragged back, the ox pulled, the man with nose cut off looking upward; no beginning, but an end.','육삼: 수레가 끌려가는 것을 보니, 그 소가 끌려가고, 그 사람이 하늘을 우러르며 코가 베였다. 처음은 없으나 끝은 있다.','六三：見輿曳，其牛掣，其人天且劓。无初有終。'),
	 (38,4,'Line 4: Opposition alone; meeting the great man, exchanging sincerity; danger, no blame.','구사: 외롭게 어긋났으나, 원부를 만나 믿음을 교제하니, 위태로우나 허물은 없다.','九四：睽孤，遇元夫，交孚，厲无咎。'),
	 (38,5,'Line 5: Regret disappears. His clan bites through the flesh; what blame in going forward?','육오: 뉘우침이 없어지니, 그 종친이 살을 씹으니, 나아가면 어찌 허물이 있으랴?','六五：悔亡，厥宗噬膚，往何咎？'),
	 (38,6,'Line 6: Opposition alone; seeing a pig covered with mud, a cart full of ghosts. First drawing the bow, then relaxing it. Not a robber but a suitor; going forward, if it rains, good fortune.','상구: 외롭게 어긋났으니, 진흙 진 돼지를 보고 귀신이 한 수레 가득 실렸다. 먼저 활을 당기나 나중에 풀었다. 도적이 아니라 혼인하러 오는 것이니, 나아가다 비를 만나면 길하다.','上九：睽孤，見豕負塗，載鬼一車，先張之弧，後說之弧。匪寇婚媾，往遇雨則吉。'),
	 (39,1,'Line 1: Going leads to obstruction; coming brings honor.','초육: 가면 막히나 오면 명예가 있다.','初六：往蹇，來譽。'),
	 (39,2,'Line 2: The king’s servant faces obstruction; not due to his own fault.','육이: 임금의 신하가 애써도, 자신 때문이 아니다.','六二：王臣蹇蹇，匪躬之故。');
INSERT INTO hexaoracle.hexagram_line (hexagram_id,line_index,text_en,text_ko,text_zh) VALUES
	 (39,3,'Line 3: Going leads to obstruction; returning brings reversal.','구삼: 가면 막히고, 돌아오면 오히려 낫다.','九三：往蹇，來反。'),
	 (39,4,'Line 4: Going leads to obstruction; coming brings union.','육사: 가면 막히고, 오면 연합한다.','六四：往蹇，來連。'),
	 (39,5,'Line 5: Great obstruction; friends arrive.','구오: 크게 막히나 벗이 온다.','九五：大蹇，朋來。'),
	 (39,6,'Line 6: Going leads to obstruction; coming brings great gain, good fortune. Beneficial to see the great man.','상육: 가면 막히고, 오면 크게 얻으니 길하다. 대인을 뵈는 것이 이롭다.','上六：往蹇，來碩，吉；利見大人。'),
	 (40,1,'Line 1: No blame.','초육: 허물이 없다.','初六：无咎。'),
	 (40,2,'Line 2: In hunting, catching three foxes, obtaining yellow arrows; perseverance brings good fortune.','구이: 사냥에서 세 마리 여우를 잡고, 노란 화살을 얻으니, 바르게 하면 길하다.','九二：田獲三狐，得黃矢，貞吉。'),
	 (40,3,'Line 3: Bearing burdens while riding in a carriage invites robbers; perseverance brings humiliation.','육삼: 짐을 지고 또 수레를 타니, 도적을 불러오니, 바르더라도 인색하다.','六三：負且乘，致寇至，貞吝。'),
	 (40,4,'Line 4: Release from the toe; friends arrive bringing trust.','구사: 엄지발가락을 풀어주니, 벗이 와서 믿음을 준다.','九四：解而拇，朋至斯孚。'),
	 (40,5,'Line 5: The noble one has deliverance; good fortune. He gains trust even among petty men.','육오: 군자가 해로움을 풀면 길하니, 소인에게도 믿음을 얻게 된다.','六五：君子維有解，吉；有孚于小人。'),
	 (40,6,'Line 6: The duke shoots a falcon on a high wall and captures it; nothing is unfavorable.','상육: 공이 높은 성벽 위의 매를 쏘아 잡으니, 이롭지 않음이 없다.','上六：公用射隼于高墉之上，獲之，无不利。');
INSERT INTO hexaoracle.hexagram_line (hexagram_id,line_index,text_en,text_ko,text_zh) VALUES
	 (41,1,'Line 1: Affairs completed, hastening forward; no blame. Consider decreasing.','초구: 일을 이미 마치고 빨리 가니 허물이 없으니, 줄임을 살펴야 한다.','初九：已事遄往，无咎，酌損之。'),
	 (41,2,'Line 2: Perseverance is beneficial; to advance brings misfortune. Without decrease there is increase.','구이: 바르게 하면 이롭고, 나아가면 흉하다. 덜지 않으면 더해진다.','九二：利貞，征凶。弗損益之。'),
	 (41,3,'Line 3: Three go together, one is reduced; one goes alone, he gains a companion.','육삼: 세 사람이 함께 가면 한 사람이 줄어들고, 한 사람이 가면 벗을 얻는다.','六三：三人行，則損一人；一人行，則得其友。'),
	 (41,4,'Line 4: Decreasing his illness; hastening brings joy; no blame.','육사: 그 병을 덜게 하니, 빨리 기쁨이 있어 허물이 없다.','六四：損其疾，使遄有喜，无咎。'),
	 (41,5,'Line 5: Perhaps increasing it with ten pairs of tortoises; cannot oppose it; great fortune.','육오: 혹은 열 거북으로 보태주니, 어길 수 없어 크게 길하다.','六五：或益之十朋之龜，弗克違，元吉。'),
	 (41,6,'Line 6: Neither decreasing nor increasing; no blame. Perseverance brings good fortune. To advance, one gains servants but has no household.','상구: 덜지도 않고 더하지도 않으니 허물이 없고, 바르면 길하다. 나아가면 신하를 얻으나 집은 없다.','上九：弗損益之，无咎，貞吉，有攸往，得臣无家。'),
	 (42,1,'Line 1: Beneficial to undertake great works; great fortune, no blame.','초구: 크게 일을 일으킴이 이로우니, 크게 길하고 허물이 없다.','初九：利用爲大作，元吉，无咎。'),
	 (42,2,'Line 2: Perhaps increasing with ten pairs of tortoises; cannot oppose it. Lasting perseverance brings fortune. The king uses it to present offerings to the Supreme Deity; good fortune.','육이: 혹 열 거북으로 보태주니 거스를 수 없어 길게 바르게 하면 길하다. 왕이 제에게 제사를 드리니 길하다.','六二：或益之十朋之龜，弗克違，永貞吉。王用享于帝，吉。'),
	 (42,3,'Line 3: Increasing with unfortunate matters; no blame. With sincerity, following the middle way; reporting to the prince with a jade tablet.','육삼: 흉한 일을 더함이니 허물이 없다. 믿음을 가지고 중도를 행하니, 옥홀로써 공에게 아뢴다.','六三：益之用凶事，无咎。有孚中行，告公用圭。'),
	 (42,4,'Line 4: Proceeding in the middle way; reporting to the prince who follows. Beneficial to rely upon this to move the state.','육사: 중도를 행하니, 공에게 아뢰면 따른다. 의지하여 나라를 옮김이 이롭다.','六四：中行，告公從。利用為依遷國。');
INSERT INTO hexaoracle.hexagram_line (hexagram_id,line_index,text_en,text_ko,text_zh) VALUES
	 (42,5,'Line 5: With sincerity and a benevolent heart; do not ask, great fortune. Sincerity bestows virtue on me.','구오: 믿음 있고 은혜로운 마음이 있으니 묻지 않아도 크게 길하다. 믿음이 있어 나의 덕을 은혜롭게 한다.','九五：有孚惠心，勿問元吉。有孚惠我德。'),
	 (42,6,'Line 6: Nothing further increases it; some strike it. If the will is not lasting, misfortune.','상구: 더함이 없고 혹 치니, 마음을 세워 오래하지 못하면 흉하다.','上九：莫益之，或擊之，立心勿恆，凶。'),
	 (43,1,'Line 1: Vigorous in the toes; advancing without being able to prevail brings blame.','초구: 앞 발가락에 힘을 쓰니, 나아가 이기지 못하면 허물이 된다.','初九：壯于前趾，往不勝為咎。'),
	 (43,2,'Line 2: Alarmed shouting; at night there are troops, yet have no fear.','구이: 두려워 외치니, 밤에 적병이 있으나 근심하지 말라.','九二：惕號，莫夜有戎，勿恤。'),
	 (43,3,'Line 3: Vigorous in the cheeks; misfortune. The noble one resolutely decides, walking alone, meets rain, becomes soaked and annoyed, yet no blame.','구삼: 뺨에 힘을 쓰니 흉하다. 군자가 결단하여 홀로 가다 비를 만나 젖으니 원망이 있으나 허물은 없다.','九三：壯于頄，有凶。君子夬夬，獨行遇雨，若濡有愠，无咎。'),
	 (43,4,'Line 4: The buttocks have no flesh, movement is halting. Leading a sheep removes regret, yet words are not believed.','구사: 엉덩이에 살이 없어 그 걸음이 머뭇거리니, 양을 끌면 뉘우침이 없으나 말을 들어도 믿지 않는다.','九四：臀无膚，其行次且。牽羊悔亡，聞言不信。'),
	 (43,5,'Line 5: Resolute as amaranth and mulberry; following the middle way brings no blame.','구오: 비름과 모시풀같이 결단하니, 중도를 행하면 허물이 없다.','九五：莧陸夬夬，中行无咎。'),
	 (43,6,'Line 6: No cry is raised; in the end, misfortune.','상육: 부르짖음이 없으니, 마침내 흉하다.','上六：无號，終有凶。'),
	 (44,1,'Line 1: Bound with a metal brake; perseverance brings good fortune. If one advances, misfortune is seen. A lean pig walks with confidence, stamping its feet.','초육: 쇠나무에 매이니 바르면 길하다. 나아가면 흉함을 본다. 여윈 돼지가 진실하여 발을 구른다.','初六：繫于金柅，貞吉；有攸往，見凶。羸豕孚蹢躅。'),
	 (44,2,'Line 2: There is fish in the basket; no blame. It is not favorable to entertain guests.','구이: 그릇에 물고기가 있으니 허물이 없으나, 손님을 맞음은 이롭지 않다.','九二：包有魚，无咎；不利賓。');
INSERT INTO hexaoracle.hexagram_line (hexagram_id,line_index,text_en,text_ko,text_zh) VALUES
	 (44,3,'Line 3: The buttocks have no flesh, movement is halting; danger, yet no great blame.','구삼: 엉덩이에 살이 없어 그 걸음이 머뭇거리니, 위태로우나 큰 허물은 없다.','九三：臀无膚，其行次且，厲，无大咎。'),
	 (44,4,'Line 4: No fish in the basket; misfortune.','구사: 그릇에 물고기가 없으니 흉하다.','九四：包无魚，起凶。'),
	 (44,5,'Line 5: With thorny branches covering the melon; containing brilliance, yet it falls from heaven.','구오: 기름나무로 오이를 싸니, 아름다움을 품었으나 하늘로부터 떨어진다.','九五：以杞包瓜，含章，有隕自天。'),
	 (44,6,'Line 6: Encountering by the horns; regret, yet no blame.','상구: 뿔로 만남이니 인색하나 허물은 없다.','上九：姤其角，吝，无咎。'),
	 (45,1,'Line 1: Sincerity not lasting, disorder and gathering. If one cries out loudly, handfuls come and bring laughter. No need to worry; to advance brings no blame.','초육: 믿음이 끝내지 못하고 어지러이 모이니, 만약 크게 외쳐 한 움큼 모으면 웃게 된다. 근심하지 말라, 나아가도 허물이 없다.','初六：有孚不終，乃亂乃萃，若號一握為笑，勿恤，往无咎。'),
	 (45,2,'Line 2: Drawing brings good fortune, no blame. With sincerity, it is beneficial to offer sacrifice.','육이: 이끌어 길하니 허물이 없다. 믿음을 두니 제사를 드림이 이롭다.','六二：引吉，无咎，孚乃利用禴。'),
	 (45,3,'Line 3: Gathering with sighs; nothing is beneficial. To advance brings no blame, slight humiliation.','육삼: 모이나 탄식하니 이로움이 없다. 나아가도 허물은 없으나 작은 인색함이 있다.','六三：萃如，嗟如，无攸利。往无咎，小吝。'),
	 (45,4,'Line 4: Great fortune; no blame.','구사: 크게 길하니 허물이 없다.','九四：大吉，无咎。'),
	 (45,5,'Line 5: Gathering with position; no blame. Without sincerity, yet lasting perseverance removes regret.','구오: 모임에 지위가 있으니 허물이 없다. 믿음이 아니어도 오래도록 바르면 뉘우침이 없다.','九五：萃有位，无咎。匪孚，元永貞，悔亡。'),
	 (45,6,'Line 6: Lamenting with tears and sighs; no blame.','상육: 눈물을 흘리며 근심하나 허물이 없다.','上六：齎咨涕洟，无咎。');
INSERT INTO hexaoracle.hexagram_line (hexagram_id,line_index,text_en,text_ko,text_zh) VALUES
	 (46,1,'Line 1: True ascent; great fortune.','초육: 참되게 오르니 크게 길하다.','初六：允升，大吉。'),
	 (46,2,'Line 2: Sincerity; it is beneficial to offer sacrifice. No blame.','구이: 믿음이 있으니 제사를 드림이 이로우니 허물이 없다.','九二：孚乃利用禴，无咎。'),
	 (46,3,'Line 3: Ascending an empty city.','구삼: 비어 있는 읍에 오르다.','九三：升虛邑。'),
	 (46,4,'Line 4: The king offers sacrifice on Mount Qi; good fortune, no blame.','육사: 왕이 기산에서 제사를 드리니, 길하여 허물이 없다.','六四：王用亨于岐山，吉无咎。'),
	 (46,5,'Line 5: Perseverance brings fortune; ascending the steps.','육오: 바르게 하니 길하여 층계에 오른다.','六五：貞吉，升階。'),
	 (46,6,'Line 6: Ascending in the dark; perseverance without ceasing is beneficial.','상육: 어둠 속에서 오르니, 그치지 않는 바름이 이롭다.','上六：冥升，利于不息之貞。'),
	 (47,1,'Line 1: Buttocks in constraint among the stump of a tree; entering a dark valley, for three years one does not see.','초육: 엉덩이가 그루터기에 곤궁하여 그윽한 골짜기에 들어가니 삼 년 동안 보지 못한다.','初六：臀困于株木，入于幽谷，三歲不覿。'),
	 (47,2,'Line 2: Oppressed by wine and food; a red sash comes forth; beneficial to make offering.','구이: 술과 음식에 곤궁하니, 붉은 인끈을 한 자가 와서 제사 드림이 이롭다.','九二：困于酒食，朱紱方來，利用享祀。'),
	 (47,3,'Line 3: Oppressed by rocks, leaning on thorns; entering the house, one does not see the wife; misfortune.','육삼: 바위에 곤궁하고 엉겅퀴에 기대니, 집에 들어가도 아내를 보지 못하니 흉하다.','六三：困于石，據于蒺藜，入于其宮，不見其妻，凶。'),
	 (47,4,'Line 4: Coming slowly, oppressed in a metal chariot; distress, but there will be an end.','구사: 천천히 오다가 금 수레에 곤궁하니 인색하나 마침내 끝이 있다.','九四：來徐徐，困于金車，吝，有終。');
INSERT INTO hexaoracle.hexagram_line (hexagram_id,line_index,text_en,text_ko,text_zh) VALUES
	 (47,5,'Line 5: Nose cut off, feet amputated; oppressed with a red sash. Slowly there is joy; beneficial to make offering.','구오: 코 베이고 발 잘리는 형벌에 곤궁하나, 붉은 인끈에 곤궁하니, 마침내 천천히 기뻐함이 있어 제사 드림이 이롭다.','九五：劓刖，困于赤紱，乃徐有說，利用祭祀。'),
	 (47,6,'Line 6: Oppressed by creeping vines, in a precarious position. Moving brings regret. If regret, then advancing brings fortune.','상육: 칡덩굴에 곤궁하여 위태로움에 있으니, 움직이면 뉘우침이 있다. 뉘우치면 나아가 길하다.','上六：困于葛藟，于臲卼，曰動悔。有悔，征吉。'),
	 (48,1,'Line 1: The well is muddy, none may drink; an old well has no birds.','초육: 우물이 진흙투성이니 먹을 수 없고, 묵은 우물에는 새도 없다.','初六：井泥不食，舊井无禽。'),
	 (48,2,'Line 2: At the well’s gorge, shooting fish; the jug is old and leaks.','구이: 우물 골짜기에서 붕어를 쏘니, 독이 낡아 새어 버린다.','九二：井谷射鮒，瓮敝漏。'),
	 (48,3,'Line 3: The well is cleaned but not used; this makes my heart sad. One can draw from it; if the king is wise, all share its blessing.','구삼: 우물을 청소해도 마시지 않으니 내 마음이 아프다. 길어다 쓸 수 있으니, 임금이 밝으면 함께 그 복을 받는다.','九三：井渫不食，為我心惻。可用汲，王明，並受其福。'),
	 (48,4,'Line 4: The well is lined; no blame.','육사: 우물을 쌓으니 허물이 없다.','六四：井甃，无咎。'),
	 (48,5,'Line 5: The well is clear; cold spring water is drunk.','구오: 우물이 차가우니, 찬 샘물을 먹는다.','九五：井冽，寒泉食。'),
	 (48,6,'Line 6: The well is not covered but is well used; with sincerity, great fortune.','상육: 우물을 덮지 않고 거두니, 믿음이 있어 크게 길하다.','上六：井收勿幕，有孚元吉。'),
	 (49,1,'Line 1: Binding with the hide of a yellow ox.','초구: 누런 소가죽으로 단단히 묶는다.','初九：鞏用黃牛之革。'),
	 (49,2,'Line 2: On the day of one’s own fate, the revolution is carried out. To advance brings good fortune, no blame.','육이: 제 날에 혁명을 이루니, 나아가면 길하고 허물이 없다.','六二：己日乃革之，征吉，无咎。');
INSERT INTO hexaoracle.hexagram_line (hexagram_id,line_index,text_en,text_ko,text_zh) VALUES
	 (49,3,'Line 3: Advancing brings misfortune, perseverance brings danger. Revolution repeated three times brings conviction.','구삼: 나아가면 흉하고, 바르면 위태롭다. 혁명의 말이 세 번 이루어지니 믿음이 있다.','九三：征凶，貞厲；革言三就，有孚。'),
	 (49,4,'Line 4: Regret vanishes. With sincerity, changing the mandate brings good fortune.','구사: 뉘우침이 없어지고, 믿음을 가지고 명을 고치니 길하다.','九四：悔亡，有孚改命，吉。'),
	 (49,5,'Line 5: The great man changes like a tiger; without divination, there is confidence.','구오: 대인이 호랑이처럼 변하니, 점치지 않아도 믿음이 있다.','九五：大人虎變，未占有孚。'),
	 (49,6,'Line 6: The noble one changes like a leopard, the petty man changes his face. Advancing brings misfortune, dwelling in perseverance brings good fortune.','상육: 군자는 표범처럼 변하고, 소인은 얼굴만 바꾸니, 나아가면 흉하고 머물러 바르게 하면 길하다.','上六：君子豹變，小人革面，征凶，居貞吉。'),
	 (50,1,'Line 1: The cauldron is overturned, its feet upward. It is beneficial to remove what is spoiled. Gaining a concubine for her son; no blame.','초육: 솥이 발이 뒤집히니, 찌꺼기를 쏟아내는 것이 이롭다. 첩을 얻어 그 아들을 두니 허물이 없다.','初六：鼎顛趾，利出否，得妾以其子，无咎。'),
	 (50,2,'Line 2: The cauldron is full. My enemy is ill and cannot approach me; good fortune.','구이: 솥에 음식이 가득하니, 나의 원수가 병들어 내게 가까이하지 못하니 길하다.','九二：鼎有實，我仇有疾，不我能即，吉。'),
	 (50,3,'Line 3: The cauldron’s ears are changed, its progress is hindered. Pheasant fat is not eaten. With rain, regret is diminished; in the end, good fortune.','구삼: 솥의 귀가 바뀌어 가다가 막히니, 꿩의 기름을 먹지 못한다. 비가 와야 뉘우침이 줄어드니, 마침내 길하다.','九三：鼎耳革，其行塞，雉膏不食，方雨虧悔，終吉。'),
	 (50,4,'Line 4: The cauldron’s legs are broken, overturning the lord’s meal. Its form is sullied; misfortune.','구사: 솥발이 부러져 공의 밥이 엎어지니, 그 모습이 더럽다. 흉하다.','九四：鼎折足，覆公餗，其形渥，凶。'),
	 (50,5,'Line 5: The cauldron has yellow ears, golden carrying rings; perseverance is beneficial.','육오: 솥의 귀가 노랗고 솥고리가 쇠로 되었으니, 바르게 함이 이롭다.','六五：鼎黃耳金鉉，利貞。'),
	 (50,6,'Line 6: The cauldron has jade rings; great fortune, nothing is unfavorable.','상구: 솥의 옥고리니, 크게 길하고 이롭지 않음이 없다.','上九：鼎玉鉉，大吉，无不利。');
INSERT INTO hexaoracle.hexagram_line (hexagram_id,line_index,text_en,text_ko,text_zh) VALUES
	 (51,1,'Line 1: Thunder comes with fear and alarm; afterward laughing and shouting, good fortune.','초구: 우레가 와서 두려워 떠나니, 뒤에는 웃으며 즐겁게 말하니 길하다.','初九：震來虩虩，後笑言啞啞，吉。'),
	 (51,2,'Line 2: Thunder comes bringing danger; losing valuables. Ascending the nine hills, do not pursue, in seven days regained.','육이: 우레가 와서 위태로워 수많은 재물을 잃으나, 아홉 언덕에 올라가니 좇지 않아도 칠일 만에 얻는다.','六二：震來厲，億喪貝，躋于九陵，勿逐，七日得。'),
	 (51,3,'Line 3: Thunder rumbles, yet walking amidst thunder brings no misfortune.','육삼: 우레가 소란스러우나, 우레 가운데 걸어가도 허물이 없다.','六三：震蘇蘇，震行无眚。'),
	 (51,4,'Line 4: Thunder reaches the mud.','구사: 우레가 진흙 속에 이른다.','九四：震遂泥。'),
	 (51,5,'Line 5: Thunder comes and goes bringing danger, yet nothing is lost; there is work to be done.','육오: 우레가 오고 가며 위태로우나, 수많은 것을 잃지 않고 일이 있다.','六五：震往來厲，億无喪，有事。'),
	 (51,6,'Line 6: Thunder terrifies, eyes bulging; to advance brings misfortune. Thunder strikes not oneself but the neighbor; no blame. There is talk in marriage.','상육: 우레에 떨며 눈이 휘둥그레지니, 나아가면 흉하다. 우레가 자기에게 미치지 않고 이웃에 미치니 허물이 없다. 혼인에는 말이 있다.','上六：震索索，視矍矍，征凶，震不于其躬，于其鄰无咎，婚媾有言。'),
	 (52,1,'Line 1: Keeping still at the toes; no blame. Lasting perseverance is beneficial.','초육: 발가락을 그치니 허물이 없고, 오래도록 바르게 하면 이롭다.','初六：艮其趾，无咎，利永貞。'),
	 (52,2,'Line 2: Keeping still at the calves; unable to rescue what follows; the heart is not glad.','육이: 장딴지를 그치니 따르는 것을 구제하지 못하여 마음이 불쾌하다.','六二：艮其腓，不拯其隨，其心不快。'),
	 (52,3,'Line 3: Keeping still at the loins; the spine is stiff; dangerous, the heart is stifled.','구삼: 허리를 그치니 척추가 늘어서니, 위태로워 마음이 답답하다.','九三：艮其限，列其夤，厲熏心。'),
	 (52,4,'Line 4: Keeping still at the body; no blame.','육사: 몸을 그치니 허물이 없다.','六四：艮其身，无咎。');
INSERT INTO hexaoracle.hexagram_line (hexagram_id,line_index,text_en,text_ko,text_zh) VALUES
	 (52,5,'Line 5: Keeping still at the jaws; words are orderly; regret vanishes.','육오: 턱을 그치니 말이 순서 있어 뉘우침이 없다.','六五：艮其輔，言有序，悔亡。'),
	 (52,6,'Line 6: Sincere stillness; good fortune.','상구: 돈독히 그치니 길하다.','上九：敦艮，吉。'),
	 (53,1,'Line 1: The wild goose gradually approaches the shore; the young one is in danger, but though there are words, no blame.','초육: 기러기가 물가에 점차 이르니, 어린 것이 위태로우나 말이 있더라도 허물은 없다.','初六：鴻漸于干，小子厲，有言，无咎。'),
	 (53,2,'Line 2: The wild goose gradually reaches the rock; it drinks and eats joyfully; good fortune.','육이: 기러기가 바위에 점차 이르니, 즐겁게 마시고 먹으니 길하다.','六二：鴻漸于磐，飲食衎衎，吉。'),
	 (53,3,'Line 3: The wild goose gradually attains the land; the husband goes forth and does not return, the wife is pregnant but does not rear. Misfortune. Beneficial to resist robbers.','구삼: 기러기가 육지에 점차 이르니, 남편이 나아가 돌아오지 않고, 아내가 임신해도 기르지 못하니 흉하다. 도적을 막음이 이롭다.','九三：鴻漸于陸，夫征不復，婦孕不育，凶；利御寇。'),
	 (53,4,'Line 4: The wild goose gradually reaches the tree; perhaps it gains a branch; no blame.','육사: 기러기가 나무에 점차 오르니, 혹 들보를 얻으니 허물이 없다.','六四：鴻漸于木，或得其桷，无咎。'),
	 (53,5,'Line 5: The wild goose gradually reaches the hill; the wife does not conceive for three years, but in the end nothing can hinder her; good fortune.','구오: 기러기가 언덕에 점차 이르니, 아내가 삼 년 동안 잉태하지 못하나, 마침내 이기지 못하니 길하다.','九五：鴻漸于陵，婦三歲不孕，終莫之勝，吉。'),
	 (53,6,'Line 6: The wild goose gradually reaches the land; its feathers can be used for ceremony; good fortune.','상구: 기러기가 육지에 점차 이르니, 그 깃을 예식에 쓸 수 있으니 길하다.','上九：鴻漸于陸，其羽可用為儀，吉。'),
	 (54,1,'Line 1: The marrying maiden as a concubine; though lame, she can walk. To advance brings good fortune.','초구: 계집이 아랫동서로 시집가니, 절름발이라도 걸을 수 있으니 나아가면 길하다.','初九：歸妹以娣，跛能履，征吉。'),
	 (54,2,'Line 2: Though one-eyed, he can see; beneficial for the hermit’s perseverance.','구이: 애꾸라도 볼 수 있으니, 은자의 바름이 이롭다.','九二：眇能視，利幽人之貞。');
INSERT INTO hexaoracle.hexagram_line (hexagram_id,line_index,text_en,text_ko,text_zh) VALUES
	 (54,3,'Line 3: The marrying maiden waits; she returns as a concubine.','육삼: 계집이 기다리다가 시집가니, 되돌아와 아랫동서가 된다.','六三：歸妹以須，反歸以娣。'),
	 (54,4,'Line 4: The marrying maiden delays marriage; in time she marries.','구사: 계집이 시집갈 때를 어기니, 늦게라도 시집가게 된다.','九四：歸妹愆期，遲歸有時。'),
	 (54,5,'Line 5: The sovereign Yi marries off his younger sister; the ruler’s robe is not as fine as that of the concubine. As the moon nearly full, good fortune.','육오: 제을이 아우를 시집보내니, 임금의 소매가 아랫동서의 소매만 같지 못하다. 달이 거의 보름에 차니 길하다.','六五：帝乙歸妹，其君之袂，不如其娣之袂良，月幾望，吉。'),
	 (54,6,'Line 6: The woman holds a basket but it is empty; the man sacrifices a sheep but no blood flows. Nothing is beneficial.','상육: 여자가 광주리를 받들되 내용이 없고, 선비가 양을 잡되 피가 없으니 이로움이 없다.','上六：女承筐无實，士刲羊无血，无攸利。'),
	 (55,1,'Line 1: Meeting one’s mate; though it be ten days, no blame. To advance brings honor.','초육: 배필을 만나니 열흘이 지나도 허물이 없고, 나아가면 높임을 받는다.','初六：遇其配主，雖旬无咎，往有尚。'),
	 (55,2,'Line 2: Abundance veiled; at midday seeing the Dipper. Advancing brings suspicion. With sincerity bursting forth, good fortune.','육이: 덮개가 풍성하여 대낮에 북두칠성을 보니, 나아가면 의심을 얻는다. 믿음이 있으면 밝아지니 길하다.','六二：豐其蔀，日中見斗，往得疑疾，有孚發若，吉。'),
	 (55,3,'Line 3: Abundance overflowing; at midday seeing darkness. Breaking the right arm; no blame.','구삼: 무성함이 넘쳐 대낮에도 어두움을 보니, 오른팔이 꺾이지만 허물은 없다.','九三：豐其沛，日中見昧，折其右肱，无咎。'),
	 (55,4,'Line 4: Abundance veiled; at midday seeing the Dipper. Meeting one’s peer; good fortune.','구사: 덮개가 풍성하여 대낮에 북두칠성을 보니, 그 평민의 주인을 만나니 길하다.','九四：豐其蔀，日中見斗，遇其夷主，吉。'),
	 (55,5,'Line 5: Coming with brilliance; there is celebration and praise; good fortune.','육오: 빛이 이르니 경사와 명예가 있으니 길하다.','六五：來章，有慶譽，吉。'),
	 (55,6,'Line 6: Abundance in the house, veiling the home. Peering through the door, it is still and empty; for three years, no one seen; misfortune.','상육: 집이 풍성하나 덮개가 가리니, 문을 엿보아도 적막하여 사람이 없고, 삼 년 동안 만나지 못하니 흉하다.','上六：豐其屋，蔀其家，闚其戶，闃其无人，三歲不覿，凶。');
INSERT INTO hexaoracle.hexagram_line (hexagram_id,line_index,text_en,text_ko,text_zh) VALUES
	 (56,1,'Line 1: The wanderer is petty and trivial; this brings disaster upon himself.','초육: 나그네가 자질구레하게 굴면 스스로 재앙을 불러온다.','初六：旅瑣瑣，斯其所取災。'),
	 (56,2,'Line 2: The wanderer rests at an inn, keeping his possessions; he gains a serving boy with perseverance.','육이: 나그네가 여관에 머물며 재물을 지니니, 동자가 바르게 섬긴다.','六二：旅即次，懷其資，得童僕貞。'),
	 (56,3,'Line 3: The wanderer’s lodging is burned; he loses his servant. Perseverance brings danger.','구삼: 나그네가 머무는 곳이 불타고 동자를 잃으니, 바르게 해도 위태롭다.','九三：旅焚其次，喪其童僕，貞厲。'),
	 (56,4,'Line 4: The wanderer rests in a place and gains property, yet my heart is not glad.','구사: 나그네가 머무는 곳에서 재물을 얻으나 내 마음이 불쾌하다.','九四：旅于處，得其資斧，我心不快。'),
	 (56,5,'Line 5: Shooting a pheasant, losing one arrow; in the end, receiving renown and mandate.','육오: 꿩을 쏘아 한 화살을 잃으나, 마침내 명예로운 명을 받는다.','六五：射雉，一矢亡，終以譽命。'),
	 (56,6,'Line 6: The bird burns its nest; the wanderer first laughs, then weeps and laments. Losing the cow in the open field; misfortune.','상구: 새가 둥지가 불타니 나그네가 먼저 웃고 나중에 울부짖는다. 소를 평지에서 잃으니 흉하다.','上九：鳥焚其巢，旅人先笑後號咷。喪牛于易，凶。'),
	 (57,1,'Line 1: Advancing and retreating; perseverance benefits the warrior.','초육: 나아가고 물러남이 있으니, 무인의 바름이 이롭다.','初六：進退，利武人之貞。'),
	 (57,2,'Line 2: Penetrating beneath the bed; employing shamans and diviners. Though confusing, good fortune, no blame.','구이: 바람이 침상 밑에 스미니, 사관과 무당을 쓰니 어지럽지만 길하고 허물이 없다.','九二：巽在床下，用史巫紛若，吉无咎。'),
	 (57,3,'Line 3: Repeated penetration; humiliation.','구삼: 자주 스미니 인색하다.','九三：頻巽，吝。'),
	 (57,4,'Line 4: Regret vanishes; in hunting, three kinds of game are caught.','육사: 뉘우침이 없어지고, 사냥에서 세 마리 짐승을 얻는다.','六四：悔亡，田獲三品。');
INSERT INTO hexaoracle.hexagram_line (hexagram_id,line_index,text_en,text_ko,text_zh) VALUES
	 (57,5,'Line 5: Perseverance brings fortune, regret vanishes, nothing is unfavorable. No beginning, but an end. Three days before and after the Geng day; good fortune.','구오: 바르게 하면 길하고 뉘우침이 없으며, 이롭지 않음이 없다. 처음은 없으나 끝이 있다. 경일 사흘 전후로 길하다.','九五：貞吉，悔亡，无不利。无初有終。先庚三日，後庚三日，吉。'),
	 (57,6,'Line 6: Penetrating beneath the bed; losing property and axe. Perseverance brings misfortune.','상구: 바람이 침상 밑에 스미니, 재물을 잃으니 바르게 해도 흉하다.','上九：巽在床下，喪其資斧，貞凶。'),
	 (58,1,'Line 1: Harmonious joy; good fortune.','초구: 기쁘게 화합하니 길하다.','初九：和兌，吉。'),
	 (58,2,'Line 2: Sincere joy; good fortune, regret vanishes.','구이: 믿음으로 기뻐하니 길하고, 뉘우침이 없어진다.','九二：孚兌，吉，悔亡。'),
	 (58,3,'Line 3: Coming joy; misfortune.','육삼: 기쁨이 찾아오니 흉하다.','六三：來兌，凶。'),
	 (58,4,'Line 4: Negotiating joy unsettled; though there is distress, there is also joy.','구사: 기쁨을 의논하나 편안하지 못하니, 병이 있으나 기쁨이 있다.','九四：商兌未寧，介疾有喜。'),
	 (58,5,'Line 5: Sincerity in stripping away; danger.','구오: 믿음이 깎이니 위태롭다.','九五：孚于剝，有厲。'),
	 (58,6,'Line 6: Attracting joy.','상육: 기쁨을 끌어들이니.','上六：引兌。'),
	 (59,1,'Line 1: Using strong horses to rescue; good fortune.','초육: 건장한 말로 구원하니 길하다.','初六：用拯馬壯，吉。'),
	 (59,2,'Line 2: Dispersion hastens to its place; regret vanishes.','구이: 흩어짐이 제 자리에 달려가니 뉘우침이 없어진다.','九二：渙奔其机，悔亡。');
INSERT INTO hexaoracle.hexagram_line (hexagram_id,line_index,text_en,text_ko,text_zh) VALUES
	 (59,3,'Line 3: Dispersion of the self; no regret.','육삼: 몸을 흩어지게 하니 뉘우침이 없다.','六三：渙其躬，无悔。'),
	 (59,4,'Line 4: Dispersion of the group; great fortune.','육사: 무리를 흩어지게 하니 크게 길하다.','六四：渙其群，元吉。'),
	 (59,5,'Line 5: Dispersing by issuing a great command; the king establishes his domain; no blame.','구오: 크게 부르짖어 흩어지게 하니, 왕이 거처를 정하니 허물이 없다.','九五：渙汗其大號，渙王居，无咎。'),
	 (59,6,'Line 6: Dispersion of blood; going far away, no blame.','상구: 피를 흩어져 멀리 나아가니 허물이 없다.','上九：渙其血，去逖出，无咎。'),
	 (60,1,'Line 1: Not going out of the door and courtyard; no blame.','초구: 문과 뜰을 나가지 않으니 허물이 없다.','初九：不出戶庭，无咎。'),
	 (60,2,'Line 2: Not going out of the gate and courtyard; misfortune.','구이: 문과 뜰을 나가지 않으니 흉하다.','九二：不出門庭，凶。'),
	 (60,3,'Line 3: If one does not practice limitation, one laments; no blame.','육삼: 절제하지 않으면 탄식하게 되니, 허물이 없다.','六三：不節若，則嗟若，无咎。'),
	 (60,4,'Line 4: Content in limitation; success.','육사: 절제함을 편안히 여기니 형통하다.','六四：安節，亨。'),
	 (60,5,'Line 5: Sweet limitation; good fortune. To advance brings honor.','구오: 절제를 달게 여기니 길하고, 나아가면 높임을 받는다.','九五：甘節，吉；往有尚。'),
	 (60,6,'Line 6: Bitter limitation; perseverance brings misfortune, yet regret vanishes.','상육: 괴로운 절제이니, 바르면 흉하나 뉘우침은 없어진다.','上六：苦節，貞凶，悔亡。');
INSERT INTO hexaoracle.hexagram_line (hexagram_id,line_index,text_en,text_ko,text_zh) VALUES
	 (61,1,'Line 1: Preparation brings good fortune. If there are other distractions, one will not be at peace.','초구: 미리 준비하면 길하나, 다른 데 마음을 두면 편안하지 않다.','初九：虞吉，有它不燕。'),
	 (61,2,'Line 2: A crane calls in the shade; its young respond. I have fine wine; I share it with you.','구이: 학이 그늘에서 울면 그 새끼가 화답한다. 내게 좋은 술이 있으니 너와 함께하리라.','九二：鳴鶴在陰，其子和之，我有好爵，吾與爾靡之。'),
	 (61,3,'Line 3: Meeting an adversary; sometimes striking, sometimes stopping, sometimes weeping, sometimes singing.','육삼: 적을 만나 혹 북을 치고 혹 그치며, 혹 울고 혹 노래한다.','六三：得敵，或鼓或罷，或泣或歌。'),
	 (61,4,'Line 4: The moon nearly full; the horse loses its mate; no blame.','육사: 달이 거의 보름에 차고, 말이 짝을 잃으니 허물이 없다.','六四：月幾望，馬匹亡，无咎。'),
	 (61,5,'Line 5: Sincerity bound together; no blame.','구오: 믿음이 얽혀 있으니 허물이 없다.','九五：有孚攣如，无咎。'),
	 (61,6,'Line 6: The wild goose’s call rises to heaven; perseverance brings misfortune.','상구: 학의 소리가 하늘에 오르니, 바르게 해도 흉하다.','上九：翰音登于天，貞凶。'),
	 (62,1,'Line 1: A flying bird brings misfortune.','초육: 나는 새가 흉하다.','初六：飛鳥以凶。'),
	 (62,2,'Line 2: Passing the grandfather, meeting the grandmother. Not reaching the ruler, meeting the minister; no blame.','육이: 조부를 지나치고, 비조모를 만난다. 임금에게 미치지 못하고 신하를 만나니 허물이 없다.','六二：過其祖，遇其妣；不及其君，遇其臣；无咎。'),
	 (62,3,'Line 3: Not exceeding, but defending; following, one may be harmed; misfortune.','구삼: 지나치지 않고 막아내니, 따라가다 해치니 흉하다.','九三：弗過防之，從或戕之，凶。'),
	 (62,4,'Line 4: No blame. Not exceeding, but meeting. To advance brings danger, be cautious. Do not use lasting perseverance.','구사: 허물은 없으나 지나치지 않고 만나니, 나아가면 위태로우니 반드시 경계해야 한다. 오래도록 바르게 함은 쓰지 말라.','九四：无咎，弗過遇之，往厲必戒，勿用永貞。');
INSERT INTO hexaoracle.hexagram_line (hexagram_id,line_index,text_en,text_ko,text_zh) VALUES
	 (62,5,'Line 5: Dense clouds without rain from our western suburbs. The prince shoots and takes it in the cave.','육오: 짙은 구름이 비를 내리지 않고 서쪽 들판에 있으니, 공이 활을 쏘아 굴속에 있는 그것을 잡는다.','六五：密雲不雨，自我西郊，公弋取彼在穴。'),
	 (62,6,'Line 6: Not meeting but exceeding; the flying bird departs. Misfortune; this is called calamity and trouble.','상육: 만나지 않고 지나치니, 새가 날아 떠나니 흉하다. 이를 재앙이라 이른다.','上六：弗遇過之，飛鳥離之，凶，是謂災眚。'),
	 (63,1,'Line 1: Dragging the wheels, the tail gets wet; no blame.','초구: 수레 바퀴를 끌어 꼬리가 젖으니 허물이 없다.','初九：曳其輪，濡其尾，无咎。'),
	 (63,2,'Line 2: The woman loses her curtain; do not pursue it, in seven days it is obtained.','육이: 아내가 수레 덮개를 잃었으나, 좇지 않아도 칠일 만에 얻는다.','六二：婦喪其茀，勿逐，七日得。'),
	 (63,3,'Line 3: The High Ancestor attacked the Demon Region; in three years he conquered it. Do not employ petty men.','구삼: 고종이 귀방을 정벌하여 삼 년 만에 이겼으니, 소인을 쓰지 말라.','九三：高宗伐鬼方，三年克之，小人勿用。'),
	 (63,4,'Line 4: The boat is patched with rags; all day long be cautious.','육사: 배가 헝겊을 덧대어 기운 듯하니, 종일토록 경계해야 한다.','六四：繻有衣袽，終日戒。'),
	 (63,5,'Line 5: The eastern neighbor slaughters an ox; not as good as the western neighbor’s simple offering. Truly receiving the blessing.','구오: 동쪽 이웃이 소를 잡는 것보다 서쪽 이웃이 간소하게 제사 드림이 더하니, 참으로 그 복을 받는다.','九五：東鄰殺牛，不如西鄰之禴祭，實受其福。'),
	 (63,6,'Line 6: The head gets wet; danger.','상육: 머리가 젖으니 위태롭다.','上六：濡其首，厲。'),
	 (64,1,'Line 1: The tail gets wet; humiliation.','초육: 꼬리가 젖으니 인색하다.','初六：濡其尾，吝。'),
	 (64,2,'Line 2: Dragging the wheels; perseverance brings good fortune.','구이: 바퀴를 끌어가니 바르게 하면 길하다.','九二：曳其輪，貞吉。');
INSERT INTO hexaoracle.hexagram_line (hexagram_id,line_index,text_en,text_ko,text_zh) VALUES
	 (64,3,'Line 3: Before completion; to advance brings misfortune, yet it is beneficial to cross the great river.','육삼: 아직 건너지 못했으니, 나아가면 흉하나 큰 내를 건넘이 이롭다.','六三：未濟，征凶，利涉大川。'),
	 (64,4,'Line 4: Perseverance brings good fortune, regret vanishes. Thunder strikes the Demon Region; in three years, rewards are granted by the great state.','구사: 바르게 하면 길하고 뉘우침이 없으며, 우레가 귀방을 치니 삼 년 만에 대국에서 상을 받는다.','九四：貞吉，悔亡。震用伐鬼方，三年有賞于大國。'),
	 (64,5,'Line 5: Perseverance brings good fortune, no regret. The noble one’s radiance is sincere; good fortune.','육오: 바르게 하면 길하고 뉘우침이 없다. 군자의 빛이 성실하니 길하다.','六五：貞吉，无悔。君子之光，有孚，吉。'),
	 (64,6,'Line 6: With sincerity in drinking wine, no blame. If the head gets wet, with sincerity it is lost — this is a fault.','상구: 믿음이 있어 술을 마시면 허물이 없으나, 머리가 젖으면 믿음을 잃어 잘못된다.','上九：有孚于飲酒，无咎。濡其首，有孚失是。');
